import { Developer } from "../models/developer.model.js";
import { Skill } from "../models/skill.model.js";
import { Job } from "../models/job.model.js";
import { Company } from "../models/company.model.js";
import { Project } from "../models/project.model.js";

export const developers: Developer[] = [
  {
    id: "DEV001",
    name: "Abhishek N",
    email: "abhishek@example.com",
    location: "Kerala, India",
    experienceYears: 2,
    bio: "Full Stack Developer specializing in React and Node.js",
    createdAt: "2026-01-10",
  },
  {
    id: "DEV002",
    name: "Arjun Menon",
    email: "arjun@example.com",
    location: "Bangalore, India",
    experienceYears: 3,
    bio: "Frontend Engineer focused on React applications",
    createdAt: "2026-01-11",
  },
  {
    id: "DEV003",
    name: "Priya Sharma",
    email: "priya@example.com",
    location: "Chennai, India",
    experienceYears: 4,
    bio: "Backend Engineer working with Node.js and PostgreSQL",
    createdAt: "2026-01-12",
  },
  {
    id: "DEV004",
    name: "Rahul Kumar",
    email: "rahul@example.com",
    location: "Hyderabad, India",
    experienceYears: 5,
    bio: "Cloud and DevOps Engineer",
    createdAt: "2026-01-13",
  },
  {
    id: "DEV005",
    name: "Sneha Raj",
    email: "sneha@example.com",
    location: "Kochi, India",
    experienceYears: 2,
    bio: "Full Stack JavaScript Developer",
    createdAt: "2026-01-14",
  },
  {
    id: "DEV006",
    name: "Vishnu Prasad",
    email: "vishnu@example.com",
    location: "Coimbatore, India",
    experienceYears: 3,
    bio: "Software Engineer specializing in TypeScript",
    createdAt: "2026-01-15",
  },
  {
    id: "DEV007",
    name: "Meera Krishnan",
    email: "meera@example.com",
    location: "Bangalore, India",
    experienceYears: 6,
    bio: "Senior Full Stack Engineer",
    createdAt: "2026-01-16",
  },
  {
    id: "DEV008",
    name: "Karthik S",
    email: "karthik@example.com",
    location: "Chennai, India",
    experienceYears: 4,
    bio: "Backend and API Developer",
    createdAt: "2026-01-17",
  },
  {
    id: "DEV009",
    name: "Ananya Das",
    email: "ananya@example.com",
    location: "Kolkata, India",
    experienceYears: 3,
    bio: "React and Next.js Developer",
    createdAt: "2026-01-18",
  },
  {
    id: "DEV010",
    name: "Nikhil Thomas",
    email: "nikhil@example.com",
    location: "Trivandrum, India",
    experienceYears: 5,
    bio: "Cloud Native Full Stack Engineer",
    createdAt: "2026-01-19",
  },
];

export const skills: Skill[] = [
  {
    id: "SK001",
    name: "JavaScript",
    category: "Programming",
  },
  {
    id: "SK002",
    name: "TypeScript",
    category: "Programming",
  },
  {
    id: "SK003",
    name: "React",
    category: "Frontend",
  },
  {
    id: "SK004",
    name: "Next.js",
    category: "Frontend",
  },
  {
    id: "SK005",
    name: "Node.js",
    category: "Backend",
  },
  {
    id: "SK006",
    name: "Express.js",
    category: "Backend",
  },
  {
    id: "SK007",
    name: "PostgreSQL",
    category: "Database",
  },
  {
    id: "SK008",
    name: "MongoDB",
    category: "Database",
  },
  {
    id: "SK009",
    name: "Docker",
    category: "DevOps",
  },
  {
    id: "SK010",
    name: "AWS",
    category: "Cloud",
  },
  {
    id: "SK011",
    name: "Git",
    category: "Tools",
  },
  {
    id: "SK012",
    name: "GraphQL",
    category: "Backend",
  },
  {
    id: "SK013",
    name: "Python",
    category: "Programming",
  },
  {
    id: "SK014",
    name: "Java",
    category: "Programming",
  },
  {
    id: "SK015",
    name: "Spring Boot",
    category: "Backend",
  },
  {
    id: "SK016",
    name: "Redis",
    category: "Database",
  },
  {
    id: "SK017",
    name: "Kubernetes",
    category: "DevOps",
  },
  {
    id: "SK018",
    name: "Tailwind CSS",
    category: "Frontend",
  },
  {
    id: "SK019",
    name: "Vue.js",
    category: "Frontend",
  },
  {
    id: "SK020",
    name: "CI/CD",
    category: "DevOps",
  },
];

export const companies: Company[] = [
  {
    id: "COMP001",
    name: "TechNova Solutions",
    industry: "Software",
    location: "Bangalore, India",
    website: "https://technova.example.com",
    employeeCount: 250,
  },
  {
    id: "COMP002",
    name: "CloudSphere Technologies",
    industry: "Cloud Computing",
    location: "Hyderabad, India",
    website: "https://cloudsphere.example.com",
    employeeCount: 400,
  },
  {
    id: "COMP003",
    name: "FinStack Labs",
    industry: "FinTech",
    location: "Chennai, India",
    website: "https://finstack.example.com",
    employeeCount: 180,
  },
  {
    id: "COMP004",
    name: "HealthSync",
    industry: "Healthcare Technology",
    location: "Kochi, India",
    website: "https://healthsync.example.com",
    employeeCount: 120,
  },
  {
    id: "COMP005",
    name: "RetailGrid",
    industry: "E-Commerce",
    location: "Mumbai, India",
    website: "https://retailgrid.example.com",
    employeeCount: 300,
  },
  {
    id: "COMP006",
    name: "DataForge",
    industry: "Data Technology",
    location: "Pune, India",
    website: "https://dataforge.example.com",
    employeeCount: 220,
  },
  {
    id: "COMP007",
    name: "AppOrbit",
    industry: "SaaS",
    location: "Coimbatore, India",
    website: "https://apporbit.example.com",
    employeeCount: 90,
  },
  {
    id: "COMP008",
    name: "DevCloud Systems",
    industry: "Cloud Software",
    location: "Delhi, India",
    website: "https://devcloud.example.com",
    employeeCount: 350,
  },
];

export const projects: Project[] = [
  {
    id: "PROJ001",
    name: "E-Commerce Platform",
    description: "Scalable online shopping platform",
    category: "E-Commerce",
    status: "COMPLETED",
    startDate: "2024-01-01",
    endDate: "2024-06-30",
  },
  {
    id: "PROJ002",
    name: "Healthcare Portal",
    description: "Patient management and appointment platform",
    category: "Healthcare",
    status: "ONGOING",
    startDate: "2025-01-01",
  },
  {
    id: "PROJ003",
    name: "Payment Gateway",
    description: "Secure payment processing platform",
    category: "FinTech",
    status: "COMPLETED",
    startDate: "2023-05-01",
    endDate: "2024-01-15",
  },
  {
    id: "PROJ004",
    name: "Cloud Monitoring System",
    description: "Infrastructure monitoring dashboard",
    category: "Cloud",
    status: "ONGOING",
    startDate: "2025-04-01",
  },
  {
    id: "PROJ005",
    name: "Recruitment Platform",
    description: "Candidate and job matching application",
    category: "HR Tech",
    status: "COMPLETED",
    startDate: "2024-02-01",
    endDate: "2024-08-30",
  },
  {
    id: "PROJ006",
    name: "Learning Management System",
    description: "Online education platform",
    category: "EdTech",
    status: "ONGOING",
    startDate: "2025-02-01",
  },
  {
    id: "PROJ007",
    name: "Analytics Dashboard",
    description: "Business intelligence dashboard",
    category: "Analytics",
    status: "COMPLETED",
    startDate: "2024-03-01",
    endDate: "2024-09-01",
  },
  {
    id: "PROJ008",
    name: "Logistics Tracker",
    description: "Real-time logistics tracking system",
    category: "Logistics",
    status: "COMPLETED",
    startDate: "2023-08-01",
    endDate: "2024-02-01",
  },
  {
    id: "PROJ009",
    name: "Social Collaboration App",
    description: "Real-time team collaboration platform",
    category: "SaaS",
    status: "ONGOING",
    startDate: "2025-05-01",
  },
  {
    id: "PROJ010",
    name: "Inventory Management System",
    description: "Warehouse and inventory management",
    category: "Enterprise",
    status: "COMPLETED",
    startDate: "2024-04-01",
    endDate: "2024-10-01",
  },
];

export const jobs: Job[] = [
  {
    id: "JOB001",
    title: "Full Stack Developer",
    description: "Build scalable web applications",
    location: "Bangalore, India",
    employmentType: "FULL_TIME",
    minExperience: 2,
    maxExperience: 5,
    salaryMin: 600000,
    salaryMax: 1000000,
    createdAt: "2026-06-01",
  },
  {
    id: "JOB002",
    title: "React Developer",
    description: "Develop modern React applications",
    location: "Chennai, India",
    employmentType: "FULL_TIME",
    minExperience: 1,
    maxExperience: 4,
    salaryMin: 500000,
    salaryMax: 850000,
    createdAt: "2026-06-02",
  },
  {
    id: "JOB003",
    title: "Node.js Developer",
    description: "Build backend APIs and services",
    location: "Hyderabad, India",
    employmentType: "FULL_TIME",
    minExperience: 2,
    maxExperience: 5,
    salaryMin: 600000,
    salaryMax: 1100000,
    createdAt: "2026-06-03",
  },
  {
    id: "JOB004",
    title: "Next.js Engineer",
    description: "Build high-performance web applications",
    location: "Remote",
    employmentType: "REMOTE",
    minExperience: 2,
    maxExperience: 5,
    salaryMin: 700000,
    salaryMax: 1200000,
    createdAt: "2026-06-04",
  },
  {
    id: "JOB005",
    title: "Backend Engineer",
    description: "Develop distributed backend systems",
    location: "Bangalore, India",
    employmentType: "FULL_TIME",
    minExperience: 3,
    maxExperience: 6,
    salaryMin: 800000,
    salaryMax: 1400000,
    createdAt: "2026-06-05",
  },
  {
    id: "JOB006",
    title: "Cloud Engineer",
    description: "Manage AWS cloud infrastructure",
    location: "Hyderabad, India",
    employmentType: "FULL_TIME",
    minExperience: 3,
    maxExperience: 7,
    salaryMin: 900000,
    salaryMax: 1500000,
    createdAt: "2026-06-06",
  },
  {
    id: "JOB007",
    title: "DevOps Engineer",
    description: "Build CI/CD and container infrastructure",
    location: "Pune, India",
    employmentType: "FULL_TIME",
    minExperience: 2,
    maxExperience: 6,
    salaryMin: 700000,
    salaryMax: 1300000,
    createdAt: "2026-06-07",
  },
  {
    id: "JOB008",
    title: "TypeScript Developer",
    description: "Build type-safe enterprise applications",
    location: "Coimbatore, India",
    employmentType: "FULL_TIME",
    minExperience: 2,
    maxExperience: 5,
    salaryMin: 500000,
    salaryMax: 950000,
    createdAt: "2026-06-08",
  },
  {
    id: "JOB009",
    title: "Software Engineer",
    description: "Develop scalable software products",
    location: "Kochi, India",
    employmentType: "FULL_TIME",
    minExperience: 1,
    maxExperience: 5,
    salaryMin: 450000,
    salaryMax: 900000,
    createdAt: "2026-06-09",
  },
  {
    id: "JOB010",
    title: "Graph Data Engineer",
    description: "Build graph-based data applications",
    location: "Remote",
    employmentType: "REMOTE",
    minExperience: 2,
    maxExperience: 6,
    salaryMin: 800000,
    salaryMax: 1400000,
    createdAt: "2026-06-10",
  },
  {
    id: "JOB011",
    title: "Java Developer",
    description: "Build enterprise Java services",
    location: "Chennai, India",
    employmentType: "FULL_TIME",
    minExperience: 2,
    maxExperience: 5,
    salaryMin: 600000,
    salaryMax: 1000000,
    createdAt: "2026-06-11",
  },
  {
    id: "JOB012",
    title: "Python Developer",
    description: "Develop data and backend applications",
    location: "Bangalore, India",
    employmentType: "FULL_TIME",
    minExperience: 2,
    maxExperience: 5,
    salaryMin: 600000,
    salaryMax: 1050000,
    createdAt: "2026-06-12",
  },
  {
    id: "JOB013",
    title: "Frontend Engineer",
    description: "Create responsive frontend experiences",
    location: "Remote",
    employmentType: "REMOTE",
    minExperience: 2,
    maxExperience: 5,
    salaryMin: 550000,
    salaryMax: 950000,
    createdAt: "2026-06-13",
  },
  {
    id: "JOB014",
    title: "API Developer",
    description: "Design REST and GraphQL APIs",
    location: "Kochi, India",
    employmentType: "FULL_TIME",
    minExperience: 2,
    maxExperience: 5,
    salaryMin: 550000,
    salaryMax: 1000000,
    createdAt: "2026-06-14",
  },
  {
    id: "JOB015",
    title: "Cloud Native Developer",
    description: "Build containerized cloud applications",
    location: "Delhi, India",
    employmentType: "FULL_TIME",
    minExperience: 3,
    maxExperience: 7,
    salaryMin: 850000,
    salaryMax: 1450000,
    createdAt: "2026-06-15",
  },
];